/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as DatasetRouteImport } from './routes/dataset'
import { Route as MethodRouteImport } from './routes/method'
import { Route as ReportTraceIdRouteImport } from './routes/report.$traceId'
import { Route as TraceTraceIdRouteImport } from './routes/trace.$traceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetRoute = DatasetRouteImport.update({
  id: '/dataset',
  path: '/dataset',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportTraceIdRoute = ReportTraceIdRouteImport.update({
  id: '/report/$traceId',
  path: '/report/$traceId',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceTraceIdRoute = TraceTraceIdRouteImport.update({
  id: '/trace/$traceId',
  path: '/trace/$traceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/dataset': typeof DatasetRoute
  '/method': typeof MethodRoute
  '/report/$traceId': typeof ReportTraceIdRoute
  '/trace/$traceId': typeof TraceTraceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/dataset': typeof DatasetRoute
  '/method': typeof MethodRoute
  '/report/$traceId': typeof ReportTraceIdRoute
  '/trace/$traceId': typeof TraceTraceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/dataset': typeof DatasetRoute
  '/method': typeof MethodRoute
  '/report/$traceId': typeof ReportTraceIdRoute
  '/trace/$traceId': typeof TraceTraceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/dataset'
    | '/method'
    | '/report/$traceId'
    | '/trace/$traceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cases'
    | '/dataset'
    | '/method'
    | '/report/$traceId'
    | '/trace/$traceId'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/dataset'
    | '/method'
    | '/report/$traceId'
    | '/trace/$traceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRoute
  DatasetRoute: typeof DatasetRoute
  MethodRoute: typeof MethodRoute
  ReportTraceIdRoute: typeof ReportTraceIdRoute
  TraceTraceIdRoute: typeof TraceTraceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataset': {
      id: '/dataset'
      path: '/dataset'
      fullPath: '/dataset'
      preLoaderRoute: typeof DatasetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$traceId': {
      id: '/report/$traceId'
      path: '/report/$traceId'
      fullPath: '/report/$traceId'
      preLoaderRoute: typeof ReportTraceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trace/$traceId': {
      id: '/trace/$traceId'
      path: '/trace/$traceId'
      fullPath: '/trace/$traceId'
      preLoaderRoute: typeof TraceTraceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRoute,
  DatasetRoute: DatasetRoute,
  MethodRoute: MethodRoute,
  ReportTraceIdRoute: ReportTraceIdRoute,
  TraceTraceIdRoute: TraceTraceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
